[profile.default]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
src = "src"
script = "script"
test = "test"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
tempo_mainnet = "${TEMPO_RPC_URL}"

[etherscan]
tempo_mainnet = { key = "unused", url = "https://contracts.tempo.xyz", chain = 4217 }
